In [7]:
import numpy as np

data1 = np.array([2,3,4,5]) #列表
data1

data2 = np.array((2,3,4)) #元组
data2

data3 = [[1,2,3,4],[9,2,3,5]] #二维数组
data3 = np.array(data3)
data3

array([[1, 2, 3, 4],
       [9, 2, 3, 5]])

In [9]:
data3.shape #查询结构：2行4列

(2, 4)

In [10]:
data3.dtype #查询数据类型

dtype('int32')

In [12]:
data4 = [1,3.45,3.1415]
array4 = np.array(data4)
array4.dtype

dtype('float64')

In [14]:
array5 = np.arange(7) #与range功能相似
array5

array([0, 1, 2, 3, 4, 5, 6])

In [15]:
array6 = np.ones((3,4))#3行4列的数组，值全为1
array6

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
array7 = np.ones_like(data3) #产生于data3相似的结构，值全为1
array7

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [18]:
array6.ndim

2

In [19]:
array6

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])